version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    env_file:
      - ../.env
volumes:
  mongodb-data:
